version: "2"

# Empty exclude so we include the tests.  By default
# Code Climate will ignore test folders.  Add additional
# excludes as needed.
#
#  https://docs.codeclimate.com/docs/default-analysis-configuration
exclude_patterns:
  - "**/obj/**"
  - "Corgibytes.Freshli.Lib.Test/**"
