exclude_patterns:
  - "Corgibytes.Freshli.Lib/obj/**"
  - "Corgibytes.Freshli.Lib.Test/obj/**"
  # Needs to be addressed in https://github.com/corgibytes/freshli/issues/236
  - "Corgibytes.Freshli.Lib/Languages/CSharp/NuGetRepository.cs"
