version: '3.7'
services:
  web:
    image: freshli.azurecr.io/freshli/web
    build:
      context: .
      dockerfile: Dockerfile.web
      target: runtime
    ports:
      - 80:80
    stdin_open: true
    tty: true
    entrypoint: ./docker-entrypoint-web.sh
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:80"
      DB_HOST: "db-host"
      DB_USERNAME: "db-user"
      DB_PASSWORD: "db-password"
      DB_NAME: "db-name" 
      DB_SSL_MODE: "Require"
  
  worker:
    image: freshli.azurecr.io/freshli/worker
    build:
      context: .
      dockerfile: Dockerfile.worker
      target: runtime    
    stdin_open: true
    tty: true
    entrypoint: ./docker-entrypoint-worker.sh
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DB_HOST: "db-host"
      DB_USERNAME: "db-user"
      DB_PASSWORD: "db-password"
      DB_NAME: "db-name"
      DB_SSL_MODE: "Require"

