name: Release Notes

on:
  push:
    branches:
      - 'main'
      - 'release*'

jobs:
  release_notes:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0 # Required for GitVersion
          ref: ${{ github.head_ref }} # Required for Git Auto Commit

      # Require .NET 5 for GitVersion and .NET 3 for GitRelesaseManager
      - name: Setup .NET Core 5 (GitVersion)
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.x

      - name: Setup .NET Core 3 (GitReleaseManager)
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 3.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.6.6'

      - name: Show GitVersion Config
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
          additionalArguments: '/showConfig'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.10
        id: gitversion
        with:
          useConfigFile: true

      - uses: gittools/actions/gitreleasemanager/setup@v0.9.10
        name: Install GitReleaseManager
        with:
          versionSpec: '0.11.0'

      - uses: gittools/actions/gitreleasemanager/create@v0.9.10
        name: Create/Update GitHub Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: 'corgibytes'
          repository: 'freshli-lib'
          milestone: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'

      # This will generate the change log for all the GitHub Releases, feature
      # is not included in the GitReleaseManager action yet.
      - name: Generate Change Log
        run: |
          dotnet-gitreleasemanager export --token ${{ secrets.GITHUB_TOKEN }} -o 'corgibytes' -r 'freshli-lib' -f 'CHANGELOG.md'
          git add --renormalize CHANGELOG.md
          cat CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        name: Commit Change Log and if it Changed
        with:
          commit_message: Committing auto generated change log.
          file_pattern: CHANGELOG.md
          commit_user_name: M. Scott Ford (as bot)
          commit_user_email: scott@corgibytes.com

