name: Release Notes

on:
  push:
    branches:
      - 'main'
      - 'release*'

jobs:
  release_notes:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          source-url: https://nuget.pkg.github.com/GitTools/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_READ_TOKEN}}

      - name: Install GitVersion
        run: dotnet tool install --global --add-source https://nuget.pkg.github.com/GitTools/index.json --version 5.8.0-beta1.138 --configfile ../nuget.config GitVersion.Tool

      - name: Show GitVersion Config
        run: dotnet gitversion /showConfig

      - name: Determine Version
        run: dotnet gitversion

      - name: Install GitReleaseManager
        run: dotnet tool install --global --add-source https://nuget.pkg.github.com/GitTools/index.json --version 0.12.1 GitReleaseManager.Tool

      # If there are no closed issues generating the Github Release will fail because it raises an exception.
      # Work around this by checking for success or no closed issue errors.
      - name: "Create/Update GitHub Release ${{ steps.gitversion.outputs.majorMinorPatch }}"
        run: |
          dotnet gitreleasemanager create --owner corgibytes --repository freshli-lib --token ${{ secrets.GITHUB_TOKEN }} --milestone v${{ steps.gitversion.outputs.majorMinorPatch }} --logFilePath output.txt || true
          cat output.txt | grep 'No closed issues have been found for milestone\|Drafted release is available at'

      # This will generate the change log for all the GitHub Releases, feature
      # is not included in the GitReleaseManager action yet.
      - name: Generate Change Log
        run: |
          dotnet gitreleasemanager export --token ${{ secrets.GITHUB_TOKEN }} -o 'corgibytes' -r 'freshli-lib' -f 'CHANGELOG.md'
          git add --renormalize CHANGELOG.md
          cat CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        name: Commit Change Log and if it Changed
        with:
          commit_message: Committing auto generated change log.
          file_pattern: CHANGELOG.md
          commit_user_name: M. Scott Ford (as bot)
          commit_user_email: scott@corgibytes.com

